### PR TITLE
feature: add typings and build with typescript compiler

### PR DESCRIPTION
**Pull request by sveisvei**
I needed typescript typings, so ended up using the typescript compiler to allow js and output sensible node compatible code.

### CODE REVIEW

**Comment by jirimoravcik** [comment]
Hello @sveisvei, we actually have a TS config available, could you please make it so you extend it? The repository is here https://github.com/apify/apify-tsconfig

**Comment by sveisvei** [comment]
@jirimoravcik fixed

`rimraf` wanted `glob` as well.

**Review by mhamas — APPROVED** [review]
looks good to me, thanks @sveisvei

**Review by jirimoravcik — APPROVED** [review]

**Comment by jirimoravcik** [comment]
@sveisvei New version is released as `1.0.1-beta.0`

**Comment by sveisvei** [comment]
@jirimoravcik Thank you, will switch to this from my fork.

**Pull request merged**
