### PR TITLE
Develop branch

### PR DESCRIPTION
**Pull request by BestNathan**
hello there,
what i did lists below

add: 
- multisheet support
- return stream when invoke `createSheetBook` which can directly write data
fix: 
- finalize is private
- deprecated `getOutputStream` and use `outputStream` getter
add:
- a tool which can unzip a .xlsx file

### CODE REVIEW

**Comment by gippy** [comment]
Looks great, I will try it out and if everything works as expected I will merge the pull request. Thank you for the improvements.

**Comment by BestNathan** [comment]
sadly it doesn't work as expected, and i'm trying my best to figure out where the problem is and commit later

**Comment by BestNathan** [comment]
but i think these new features are really useful and hope that we can together make these features better and stable for production

**Comment by francov** [comment]
Any updates on this PR? Does the multisheet support work on this branch?

**Comment by BestNathan** [comment]
> Any updates on this PR? Does the multisheet support work on this branch?

nope!

**Pull request closed without merging**
